In [ ]:
def test(**kwargs):
    for i,j in kwargs:

In [ ]:
----only contain one expression
----cannot use loop
----cannot use multiple return statements
----poor readability for complex logic
----cannot have docstring
----hard to debug
----not suitable for large programs

In [3]:
numbers = [10,20,0,5]

In [4]:
result=list(map(lambda x:100/x,numbers))

ZeroDivisionError: division by zero

In [5]:
nuber_iter = iter(numbers)

In [6]:
next(nuber_iter)

10

In [7]:
next(nuber_iter)

20

In [8]:
next(nuber_iter)

0

In [9]:
next(nuber_iter)

5

In [10]:
next(nuber_iter)

StopIteration:

In [11]:
def sq(x):
    return x**2

In [12]:
l = list(map(sq,[2,3,4,6,7,8,1013,45]))

In [13]:
l

[4, 9, 16, 36, 49, 64, 1026169, 2025]

In [14]:
def is_odd(x):
    return x%2!=0

In [15]:
l= list(filter(is_odd,[2,3,45,8,90,45,23]))

In [16]:
l

[3, 45, 45, 23]

In [ ]:
from functools import reduce

reduce(function,iterable)

In [17]:
from functools import reduce

In [20]:
l=reduce(lambda x,y:x+y,[2,3,4,5,6,7,8])

In [21]:
l

35

In [23]:
import pandas as pd

data = {
    'Month': ['Jan', 'Jan', 'Feb', 'Feb', 'Mar', 'Mar'],
    'Product': ['Laptop', 'Mobile', 'Laptop', 'Mobile', 'Laptop', 'Mobile'],
    'Sales': [50000, 30000, 60000, 40000, 55000, 35000]
}

df = pd.DataFrame(data)

In [24]:
df

  Month Product  Sales
0   Jan  Laptop  50000
1   Jan  Mobile  30000
2   Feb  Laptop  60000
3   Feb  Mobile  40000
4   Mar  Laptop  55000
5   Mar  Mobile  35000

In [25]:
pivot_df = df.pivot(index='Month',columns='Product',values='Sales')

In [26]:
pivot_df

Product  Laptop  Mobile
Month
Feb       60000   40000
Jan       50000   30000
Mar       55000   35000